esphome:
  name: "esp32-devkitv1-no2"
  friendly_name: "esp32-devkitv1-no2"

# http://localhost:4999/boards/postcreate/36181/54809
# project source code:http://localhost:4999/boards/topic/36181/esp32-vl53l0x-esphome#54809
# step 1.identify the correct ESP platform and board
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
 

ota:
  - platform: esphome
    password: "f64ede371faa967a2c64bca71ce4cf99"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32No2  Hotspot"
    password: "HSg4eoMPS0d0"

captive_portal:


# Example configuration entry
mdns:
  disabled: false

  services:
    - service: "_custom_service"
      protocol: "_tcp"
      port: 8080
      txt:
        txt_key_1: txt_value_1    

# vl53l0x for ESP32  https://esphome.io/components/i2c#i2c
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: bus_a

# https://esphome.io/components/binary_sensor/esp32_touch.html#finding-thresholds
esp32_touch:


# ttp223 https://community.home-assistant.io/t/touch-sensor-ttp223/351328/3
# https://blog.matterxiaomi.com/blog/bathroom-mirror-part4/
# ESP32 32PIN expansion board -> vcc   3v gnd  io     gpio14(D14)  capacitive touch inputs on the ESP32
binary_sensor:
  - platform: gpio
    pin: GPIO14
    name: "ttp223 Binary Touch Sensor"


sensor:
# https://esphome.io/components/sensor/dht.html#dht-temperature-humidity-sensor
# https://www.matterxiaomi.com/boards/topic/74/diy-esp8266-hc-sr501-motion-sensor-tutorial#44549
# ESP32 32PIN expansion board -> D15   3V gnd
  - platform: dht
    pin: GPIO15
    temperature:
      name: "Dht 11 Temperature"
    humidity:
      name: "Dht 11 Humidity"
    update_interval: 60s 

# https://esphome.io/components/sensor/vl53l0x.html        
  - platform: vl53l0x
    name: "VL53L0x Distance"
    address: 0x29
    update_interval: 5s
    long_range: true  
    

# Indicator Light 
# 用switch组件、或者 output + light 组件，实际效果一样，只是在前端出现的实体一个是开关一个是灯。
output:
  - platform: ledc
    pin: GPIO2    # 这里是esp32控制的板在灯的GPIO
    id: gpio_2

# Defogger heating relay
# https://chochol.io/en/smart-home/home-assistant-installing-mirror-lighting-on-esphome/
  - platform: gpio
    pin: 
      number: GPIO16
      mode:
        output: "True"
        open_drain: "True" 
    id: relay_1
    inverted: true


# Example usage in a light
light:
  - platform: monochromatic
    output: gpio_2
    name: "Indicator Light"

# Defogger heating relay light
# https://chochol.io/en/smart-home/home-assistant-installing-mirror-lighting-on-esphome/
  - platform: binary
    name: "Defogger heating relay light"
    output: relay_1
    restore_mode: ALWAYS_OFF
    id: light_1      

# come from：https://github.com/DIYSmartHome8/Asrpro-ESP8266/blob/main/esp8266/asrpro_public.yaml
button:
  - platform: restart   
    name: ESP Restart
    entity_category: config

text_sensor:
# https://community.home-assistant.io/t/esp-12f-ds18b20-not-working-on-gpio13/636264/3?u=msly
- platform: version
  name: ESPHome Version
  disabled_by_default: false
  icon: mdi:new-box
  entity_category: diagnostic
  hide_timestamp: false    

# https://esphome.io/components/text_sensor/wifi_info.html
- platform: wifi_info
  ip_address:
    name: IP
    disabled_by_default: false
    entity_category: diagnostic
    update_interval: 1s
  ssid:
    name: SSID
  bssid:
    name: BSSID
  mac_address:
    name: Mac Wifi
  dns_address:
    name: DNS    