# This is a source code created by esp32-s3-box-3b offcial project
# 
substitutions:
  name: esp32-s3-box-3-2d954c
  friendly_name: ESP32 S3 Box 3 2d954c
packages:
  esphome.voice-assistant: github://esphome/wake-word-voice-assistants/esp32-s3-box-3/esp32-s3-box-3.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: zMN8kcVTNFEeZaTMTZIvIeT50z76rBlyLyKD4dlE2Kk=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
