substitutions:
  name: esp32-bluetooth-proxy-58d270
  friendly_name: Bluetooth Proxy 58d270
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: dZJEAQ1HV9CkvLhDrDUvyCB9Su0H8Sw6V7i0QiaADRk=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

time:
  - platform: homeassistant
    id: homeassistant_time  

# https://blog.matterxiaomi.com/blog/bathroom-mirror-part5/
# https://esphome.io/components/display/tm1637
# ESP32 32PIN expansion board -> D17 D16  3V gnd
display:
  platform: tm1637
  clk_pin: GPIO17
  dio_pin: GPIO16
  update_interval: 500ms
  lambda: |-
      static int i = 0;
      i++;
      if ((i % 2) == 0)
        it.strftime("%H.%M", id(homeassistant_time).now());
      else
        it.strftime("%H%M", id(homeassistant_time).now());

# https://esphome.io/components/sensor/dht.html#dht-temperature-humidity-sensor
# https://www.matterxiaomi.com/boards/topic/74/diy-esp8266-hc-sr501-motion-sensor-tutorial#44549
# ESP32 32PIN expansion board -> D15   3V gnd
sensor:
  - platform: dht
    pin: GPIO15
    temperature:
      name: "Dht 11 Temperature"
    humidity:
      name: "Dht 11 Humidity"
    update_interval: 60s  

# https://esphome.io/components/sensor/ultrasonic.html
# https://www.matterxiaomi.com/boards/topic/2167/home-assistant-esphome-series-esp32#47664
# ESP32 32PIN expansion board -> D12 D13   5V gnd
  - platform: ultrasonic
    trigger_pin: GPIO12
    echo_pin:  GPIO13
    name: "Ultrasonic Sensor"
    update_interval: 1s
    accuracy_decimals: 2
    unit_of_measurement: m     

#
# https://www.matterxiaomi.com/boards/topic/2167/home-assistant-esphome-series-esp32#47664
# ESP32 32PIN expansion board -> D14   5V gnd
binary_sensor:
  # SR501 PIR Sensor
  - platform: gpio
    name: "SR501 PIR Sensor"
    pin: GPIO14
    device_class: motion     

 