substitutions:
  name: esp32-bluetooth-proxy-58d270
  friendly_name: Bluetooth Proxy 58d270
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: dZJEAQ1HV9CkvLhDrDUvyCB9Su0H8Sw6V7i0QiaADRk=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
