substitutions:
  name: esp32-bluetooth-proxy-58d270
  friendly_name: Bluetooth Proxy 58d270
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: dZJEAQ1HV9CkvLhDrDUvyCB9Su0H8Sw6V7i0QiaADRk=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

time:
  - platform: homeassistant
    id: homeassistant_time  

# https://blog.matterxiaomi.com/blog/bathroom-mirror-part5/
display:
  platform: tm1637
  clk_pin: GPIO17
  dio_pin: GPIO16
  update_interval: 500ms
  lambda: |-
      static int i = 0;
      i++;
      if ((i % 2) == 0)
        it.strftime("%H.%M", id(homeassistant_time).now());
      else
        it.strftime("%H%M", id(homeassistant_time).now());