esphome:
  name: esp8266-12f
  friendly_name: esp8266_12f

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "jE7LBvixXgzOJifBStz0XakdtsRhGgk35H79t+kfopc="

ota:
  - platform: esphome
    password: "29a973018fd2b20215e3ef38e8acab05"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp8266-12F Fallback Hotspot"
    password: "qzqLvkUQUlPe"

captive_portal:
    