services:
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome:2025.2.0
    volumes:
      - /data/docker/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host
    environment:
      - USERNAME=esphome
      - PASSWORD=esphome